export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PROUCT_CREATE_REQUEST ="PROUCT_CREATE_REQUEST"
export const PROUCT_CREATE_SUCCESS ="PROUCT_CREATE_SUCCESS"
export const PROUCT_CREATE_FAIL ="PROUCT_CREATE_FAIL"

export const PROUCT_DELETE_REQUEST ="PROUCT_DELETE_REQUEST"
export const PROUCT_DELETE_SUCCESS ="PROUCT_DELETE_SUCCESS"
export const PROUCT_DELETE_FAIL ="PROUCT_DELETE_FAIL"

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SEUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
